export const MARK_CHECKED_EXISTING_USER = 'MARK_CHECKED_EXISTING_USER'

export const FETCH_USER_QUERY = 'FETCH_USER_QUERY'
export const FETCH_USER_QUERY_DONE = 'FETCH_USER_QUERY_DONE'

export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const LOGOUT_USER = 'LOGOUT_USER'

export const DELETE_CURRENT_ENTRY = 'DELETE_CURRENT_ENTRY'
export const DELETE_CURRENT_ENTRY_SUCCESS = 'DELETE_CURRENT_ENTRY_SUCCESS'
export const DELETE_CURRENT_ENTRY_ERROR = 'DELETE_CURRENT_ENTRY_ERROR'

export const DELETE_ENTRY = 'DELETE_ENTRY'
export const DELETE_ENTRY_SUCCESS = 'DELETE_ENTRY_SUCCESS'
export const DELETE_ENTRY_ERROR = 'DELETE_ENTRY_ERROR'

export const SAVE_NEW_ENTRY = 'SAVE_NEW_ENTRY'
export const SAVE_NEW_ENTRY_SUCCESS = 'SAVE_NEW_ENTRY_SUCCESS'
export const SAVE_NEW_ENTRY_ERROR = 'SAVE_NEW_ENTRY_ERROR'

export const FETCH_WEEK_ENTRIES = 'FETCH_WEEK_ENTRIES'
export const FETCH_WEEK_ENTRIES_SUCCESS = 'FETCH_WEEK_ENTRIES_SUCCESS'
export const FETCH_WEEK_ENTRIES_ERROR = 'FETCH_WEEK_ENTRIES_ERROR'

export const FETCH_ROOMS = 'FETCH_ROOMS'
export const FETCH_ROOMS_SUCCESS = 'FETCH_ROOMS_SUCCESS'
export const FETCH_ROOMS_ERROR = 'FETCH_ROOMS_ERROR'

export const FETCH_ROOM_ENTRIES = 'FETCH_ROOM_ENTRIES'
export const FETCH_ROOM_ENTRIES_SUCCESS = 'FETCH_ROOM_ENTRIES_SUCCESS'
export const FETCH_ROOM_ENTRIES_ERROR = 'FETCH_ROOM_ENTRIES_ERROR'

export const FETCH_USER_ROOM_ENTRIES = 'FETCH_USER_ROOM_ENTRIES'
export const FETCH_USER_ROOM_ENTRIES_SUCCESS = 'FETCH_USER_ROOM_ENTRIES_SUCCESS'
export const FETCH_USER_ROOM_ENTRIES_ERROR = 'FETCH_USER_ROOM_ENTRIES_ERROR'

export const ADD_USER_ROOM_LINK = 'ADD_USER_ROOM_LINK'
export const ADD_USER_ROOM_LINK_SUCCESS = 'ADD_USER_ROOM_LINK_SUCCESS'
export const ADD_USER_ROOM_LINK_ERROR = 'ADD_USER_ROOM_LINK_ERROR'
